// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from leveldb.idl

package cc.eevee.djinni.leveldb;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

public enum Status {
    OK,
    NOT_FOUND,
    CORRUPTION,
    NOT_SUPPORTED,
    INVALID_ARGUMENT,
    IO_ERROR,
    NOT_OPENED,
    NOT_CLOSED,
    UNKNOWN,
    ;
}
