// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from leveldb.idl

#pragma once

#include "djinni_support.hpp"
#include "leveldb.hpp"

namespace djinni_generated {

class NativeLeveldb final : ::djinni::JniInterface<::dd::Leveldb, NativeLeveldb> {
public:
    using CppType = std::shared_ptr<::dd::Leveldb>;
    using CppOptType = std::shared_ptr<::dd::Leveldb>;
    using JniType = jobject;

    using Boxed = NativeLeveldb;

    ~NativeLeveldb();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeLeveldb>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeLeveldb>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeLeveldb();
    friend ::djinni::JniClass<NativeLeveldb>;
    friend ::djinni::JniInterface<::dd::Leveldb, NativeLeveldb>;

};

}  // namespace djinni_generated
