// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from leveldb.idl

#include "NativeWriteBatch.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeWriteBatch::NativeWriteBatch() : ::djinni::JniInterface<::dd::WriteBatch, NativeWriteBatch>("cc/eevee/djinni/leveldb/WriteBatch$CppProxy") {}

NativeWriteBatch::~NativeWriteBatch() = default;


CJNIEXPORT void JNICALL Java_cc_eevee_djinni_leveldb_WriteBatch_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::dd::WriteBatch>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_cc_eevee_djinni_leveldb_WriteBatch_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::dd::WriteBatch::create();
        return ::djinni::release(::djinni_generated::NativeWriteBatch::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_cc_eevee_djinni_leveldb_WriteBatch_00024CppProxy_native_1put(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_key, jstring j_value)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::dd::WriteBatch>(nativeRef);
        ref->put(::djinni::String::toCpp(jniEnv, j_key),
                 ::djinni::String::toCpp(jniEnv, j_value));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_cc_eevee_djinni_leveldb_WriteBatch_00024CppProxy_native_1del(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jstring j_key)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::dd::WriteBatch>(nativeRef);
        ref->del(::djinni::String::toCpp(jniEnv, j_key));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_cc_eevee_djinni_leveldb_WriteBatch_00024CppProxy_native_1clear(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::dd::WriteBatch>(nativeRef);
        ref->clear();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
