// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from leveldb.idl

#pragma once

#include <memory>
#include <string>

namespace dd {

class WriteBatch;
enum class status;

class Leveldb {
public:
    virtual ~Leveldb() {}

    static std::shared_ptr<Leveldb> create();

    virtual status open(const std::string & name) = 0;

    virtual std::string get(const std::string & key) = 0;

    virtual std::string get_def(const std::string & key, const std::string & def) = 0;

    virtual status put(const std::string & key, const std::string & value) = 0;

    virtual status del(const std::string & key) = 0;

    virtual status write(const std::shared_ptr<WriteBatch> & batch) = 0;

    virtual status close() = 0;

    virtual status result() = 0;
};

}  // namespace dd
