// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from leveldb.idl

#pragma once

#include <functional>

namespace dd {

enum class status : int {
    OK,
    NOT_FOUND,
    CORRUPTION,
    NOT_SUPPORTED,
    INVALID_ARGUMENT,
    IO_ERROR,
    NOT_OPENED,
    NOT_CLOSED,
    UNKNOWN,
};

}  // namespace dd

namespace std {

template <>
struct hash<::dd::status> {
    size_t operator()(::dd::status type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
