// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from leveldb.idl

#pragma once

#include <memory>
#include <string>

namespace dd {

class WriteBatch {
public:
    virtual ~WriteBatch() {}

    static std::shared_ptr<WriteBatch> create();

    virtual void put(const std::string & key, const std::string & value) = 0;

    virtual void del(const std::string & key) = 0;

    virtual void clear() = 0;
};

}  // namespace dd
